name: NPM Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"
      - name: Publish Library...
        run: npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NGX_SEARCH_DROPDOWN_NPM }}
